#!/bin/bash
export EDITOR="vim"

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

export TERM="xterm-256color"

#GPG
export GPG_TTY=$(tty)

function parse_git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}")"
}

function parse_screen_STY {
  if [ "$STY" == "" ]
  then echo ""
  else echo "("${STY}") "
  fi
}

RED="\[\033[0;31m\]"
YELLOW="\[\033[0;33m\]"
GREEN="\[\033[0;32m\]"
WHITE="\[\033[0;97m\]"

#PS1="$RED\$(date +%H:%M) \w $GREEN$(parse_screen_STY)$YELLOW\$(parse_git_branch)$WHITE\$ "
PS1="$RED\w $GREEN$(parse_screen_STY)$YELLOW\$(parse_git_branch)$WHITE\$ "
