#!/bin/bash
export EDITOR="nvim"

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

export TERM="xterm-256color"

#GPG
export GPG_TTY=$(tty)

function parse_git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}")"
}

function parse_screen_STY {
  if [ "$STY" == "" ]
  then echo ""
  else echo "("${STY}") "
  fi
}

RED="\[\033[0;36m\]"
YELLOW="\[\033[0;33m\]"
GREEN="\[\033[0;32m\]"
WHITE="\[\033[0;97m\]"

#PS1="$RED\$(date +%H:%M) \w $GREEN$(parse_screen_STY)$YELLOW\$(parse_git_branch)$WHITE\$ "
PS1="\[\e]0;\W\a\]$RED\w $GREEN$(parse_screen_STY)$YELLOW\$(parse_git_branch)$WHITE\$ "



eval "$(/opt/homebrew/bin/brew shellenv)"
# export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
# export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk@11/include"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/jonathanseguin/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/jonathanseguin/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/jonathanseguin/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/jonathanseguin/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# function now {
#     date +"%Y-%m-%d"
# }
#
# function last_dir {
#     cd | ls -1 -d */ | tail -n 1
# }
